import { FeedbackItem, ThemeCluster, User, Workspace } from './types';
import { generateEmbedding } from './ai/embeddings';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin',
    name: 'Alex Rivera',
    email: 'alex@loopai.io',
    role: 'ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    workspaceId: 'ws-default',
  },
  {
    id: 'usr-analyst',
    name: 'Sarah Chen',
    email: 'sarah@loopai.io',
    role: 'ANALYST',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    workspaceId: 'ws-default',
  },
  {
    id: 'usr-viewer',
    name: 'Marcus Vance',
    email: 'marcus@loopai.io',
    role: 'VIEWER',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    workspaceId: 'ws-default',
  },
];

export const INITIAL_WORKSPACE: Workspace = {
  id: 'ws-default',
  name: 'Acme SaaS Cloud',
  slug: 'acme-saas',
  createdAt: '2026-01-15T00:00:00Z',
  plan: 'Enterprise AI',
};

const RAW_FEEDBACKS = [
  {
    content: "The SSO Okta login keeps throwing session timeout errors every 20 minutes when my team is actively working. Super frustrating for our 200 developers!",
    channel: "Support Tickets" as const,
    customerName: "David Sterling (VP Eng at StripeX)",
    customerTier: "Enterprise" as const,
    mrrImpact: 48000,
    sentiment: "NEGATIVE" as const,
    sentimentScore: -0.85,
    confidenceScore: 0.95,
    themes: ["Authentication & Access"],
    subThemes: ["SSO & SAML", "Session Timeout"],
    featureArea: "Security & Access",
    status: "NEW" as const,
    urgency: "CRITICAL" as const,
    createdAt: "2026-09-07T14:32:00Z",
  },
  {
    content: "LOOP's AI auto-classification saved our product team 15 hours this week! The sentiment detection accuracy is incredible.",
    channel: "NPS Surveys" as const,
    customerName: "Elena Rostova (Head of Product)",
    customerTier: "Growth" as const,
    mrrImpact: 14400,
    sentiment: "POSITIVE" as const,
    sentimentScore: 0.92,
    confidenceScore: 0.98,
    themes: ["Dashboard & Analytics"],
    subThemes: ["Export Data (CSV/PDF)"],
    featureArea: "Core Experience",
    status: "ACTIONED" as const,
    urgency: "LOW" as const,
    createdAt: "2026-09-07T11:20:00Z",
  },
  {
    content: "We need an automatic way to download monthly VAT invoices. Right now our finance department has to message support every single month.",
    channel: "Support Tickets" as const,
    customerName: "Marco Rossi (FinOps Director)",
    customerTier: "Enterprise" as const,
    mrrImpact: 36000,
    sentiment: "NEGATIVE" as const,
    sentimentScore: -0.65,
    confidenceScore: 0.91,
    themes: ["Billing & Subscriptions"],
    subThemes: ["Invoice Generation"],
    featureArea: "Monetization",
    status: "REVIEWED" as const,
    urgency: "HIGH" as const,
    createdAt: "2026-09-06T16:45:00Z",
  },
  {
    content: "The new Slack integration bot sends real-time sentiment alerts directly to our #product-feedback channel. Team loves it!",
    channel: "Community Posts" as const,
    customerName: "Samantha Reed (CS Lead)",
    customerTier: "Growth" as const,
    mrrImpact: 12000,
    sentiment: "POSITIVE" as const,
    sentimentScore: 0.88,
    confidenceScore: 0.94,
    themes: ["Integrations & API"],
    subThemes: ["Slack & Notifications"],
    featureArea: "Ecosystem",
    status: "ACTIONED" as const,
    urgency: "LOW" as const,
    createdAt: "2026-09-06T10:15:00Z",
  },
  {
    content: "Onboarding was slightly confusing when trying to invite more than 5 members at once. The invite email links expired too quickly.",
    channel: "App Reviews" as const,
    customerName: "Jordan Miller (Tech Founder)",
    customerTier: "Starter" as const,
    mrrImpact: 4800,
    sentiment: "NEUTRAL" as const,
    sentimentScore: -0.15,
    confidenceScore: 0.86,
    themes: ["Onboarding & Setup"],
    subThemes: ["Team Invites", "Setup Wizard"],
    featureArea: "Product Adoption",
    status: "REVIEWED" as const,
    urgency: "MEDIUM" as const,
    createdAt: "2026-09-05T09:30:00Z",
  },
  {
    content: "Exporting 50k rows to CSV freezes the browser tab. We desperately need a background worker or email report option for large exports.",
    channel: "Support Tickets" as const,
    customerName: "Vikram Patel (Data Operations)",
    customerTier: "Enterprise" as const,
    mrrImpact: 52000,
    sentiment: "NEGATIVE" as const,
    sentimentScore: -0.78,
    confidenceScore: 0.93,
    themes: ["Dashboard & Analytics"],
    subThemes: ["Slow Chart Loading", "Export Data (CSV/PDF)"],
    featureArea: "Core Experience",
    status: "NEW" as const,
    urgency: "HIGH" as const,
    createdAt: "2026-09-05T15:10:00Z",
  },
  {
    content: "Sales prospect asked if we support bi-directional sync with Linear. They said this is their primary decision blocker before signing the $60k contract.",
    channel: "Sales Calls" as const,
    customerName: "Gong AI Note (Account Executive: Lisa)",
    customerTier: "Enterprise" as const,
    mrrImpact: 60000,
    sentiment: "NEUTRAL" as const,
    sentimentScore: 0.10,
    confidenceScore: 0.89,
    themes: ["Integrations & API"],
    subThemes: ["Jira / Linear Sync"],
    featureArea: "Ecosystem",
    status: "NEW" as const,
    urgency: "HIGH" as const,
    createdAt: "2026-09-04T18:00:00Z",
  },
  {
    content: "The mobile view on iPhone 15 Pro is cut off on the right side when viewing analytics charts. Buttons are hard to tap.",
    channel: "App Reviews" as const,
    customerName: "Chloe Dupont",
    customerTier: "Starter" as const,
    mrrImpact: 3200,
    sentiment: "NEGATIVE" as const,
    sentimentScore: -0.60,
    confidenceScore: 0.88,
    themes: ["Mobile & UX Responsiveness"],
    subThemes: ["Mobile Layout Glitches"],
    featureArea: "UI/UX",
    status: "NEW" as const,
    urgency: "MEDIUM" as const,
    createdAt: "2026-09-04T12:45:00Z",
  },
  {
    content: "Customer during renewal call mentioned that the Ask LOOP natural language Q&A is their CEO's favorite feature for board prep.",
    channel: "Sales Calls" as const,
    customerName: "Account Review – CloudScale Corp",
    customerTier: "Enterprise" as const,
    mrrImpact: 84000,
    sentiment: "POSITIVE" as const,
    sentimentScore: 0.95,
    confidenceScore: 0.97,
    themes: ["Dashboard & Analytics"],
    subThemes: ["Export Data (CSV/PDF)"],
    featureArea: "Core Experience",
    status: "ACTIONED" as const,
    urgency: "LOW" as const,
    createdAt: "2026-09-03T14:00:00Z",
  },
  {
    content: "We were charged for 4 extra seats without clear confirmation popup when inviting contractors. Please refund and improve seat warning dialog.",
    channel: "Support Tickets" as const,
    customerName: "Arthur Pendelton (COO)",
    customerTier: "Growth" as const,
    mrrImpact: 18000,
    sentiment: "NEGATIVE" as const,
    sentimentScore: -0.72,
    confidenceScore: 0.92,
    themes: ["Billing & Subscriptions"],
    subThemes: ["Seat & License Management", "Pricing Clarity"],
    featureArea: "Monetization",
    status: "REVIEWED" as const,
    urgency: "HIGH" as const,
    createdAt: "2026-09-03T08:20:00Z",
  },
  {
    content: "Two-factor authentication SMS codes take over 3 minutes to arrive in UK/EU region. Several users get locked out.",
    channel: "Support Tickets" as const,
    customerName: "Liam O'Connor (IT Admin)",
    customerTier: "Enterprise" as const,
    mrrImpact: 42000,
    sentiment: "NEGATIVE" as const,
    sentimentScore: -0.80,
    confidenceScore: 0.94,
    themes: ["Authentication & Access"],
    subThemes: ["MFA & OTP Failure"],
    featureArea: "Security & Access",
    status: "NEW" as const,
    urgency: "CRITICAL" as const,
    createdAt: "2026-09-02T19:10:00Z",
  },
  {
    content: "The interactive chart filters and dark mode look absolutely gorgeous. Kudos to the frontend team on the sleek UI!",
    channel: "Community Posts" as const,
    customerName: "Devin K. (Designer at PixelCraft)",
    customerTier: "Growth" as const,
    mrrImpact: 9600,
    sentiment: "POSITIVE" as const,
    sentimentScore: 0.89,
    confidenceScore: 0.93,
    themes: ["Mobile & UX Responsiveness", "Dashboard & Analytics"],
    subThemes: ["UI & Accessibility"],
    featureArea: "UI/UX",
    status: "ACTIONED" as const,
    urgency: "LOW" as const,
    createdAt: "2026-09-01T15:30:00Z",
  }
];

export const INITIAL_FEEDBACKS: FeedbackItem[] = RAW_FEEDBACKS.map((raw, idx) => ({
  id: `fb-${idx + 100}`,
  ...raw,
  workspaceId: 'ws-default',
  vector: generateEmbedding(raw.content + ' ' + raw.themes.join(' ')),
}));

export const INITIAL_THEMES: ThemeCluster[] = [
  {
    id: 'thm-1',
    name: 'Authentication & Access',
    category: 'Security & Access',
    description: 'Login issues, Okta/SAML SSO timeouts, and 2FA OTP delivery delays.',
    count: 14,
    sentimentBreakdown: {
      positive: 1,
      neutral: 2,
      negative: 11,
    },
    avgSentimentScore: -0.58,
    growthRate: 48, // ↑↑↑
    subThemes: [
      { name: 'SSO & SAML Expiry', count: 6, sampleQuote: 'Okta session timeouts every 20 mins' },
      { name: 'MFA & SMS Delays', count: 5, sampleQuote: 'SMS OTP takes 3+ minutes in EU' },
      { name: 'Password Reset', count: 3, sampleQuote: 'Reset token expired unexpectedly' },
    ],
    suggestedAction: 'Extend token lifetime to 8 hours and implement Passkey / WebAuthn support.',
    priorityScore: 92,
    revenueAtRisk: 184000,
  },
  {
    id: 'thm-2',
    name: 'Billing & Subscriptions',
    category: 'Monetization',
    description: 'Invoice downloads, prorated seat alerts, and billing clarity.',
    count: 11,
    sentimentBreakdown: {
      positive: 2,
      neutral: 2,
      negative: 7,
    },
    avgSentimentScore: -0.38,
    growthRate: 25, // ↑↑
    subThemes: [
      { name: 'Invoice PDF Download', count: 6, sampleQuote: 'Finance needs automated monthly VAT receipts' },
      { name: 'Seat Addition Alerts', count: 3, sampleQuote: 'Charged for contractor seats without modal warning' },
      { name: 'Pricing Transparency', count: 2, sampleQuote: 'Feature tier matrix is confusing' },
    ],
    suggestedAction: 'Add automated invoice download tab in settings & clear seat confirmation modal.',
    priorityScore: 78,
    revenueAtRisk: 110000,
  },
  {
    id: 'thm-3',
    name: 'Dashboard & Analytics',
    category: 'Core Experience',
    description: 'KPI charts, data load speeds, and large dataset CSV/PDF exports.',
    count: 16,
    sentimentBreakdown: {
      positive: 9,
      neutral: 3,
      negative: 4,
    },
    avgSentimentScore: 0.42,
    growthRate: 15, // ↑
    subThemes: [
      { name: 'Export Data (CSV/PDF)', count: 8, sampleQuote: 'Exporting 50k rows freezes the browser' },
      { name: 'Interactive Charts & Dark Mode', count: 5, sampleQuote: 'Recharts visualizations look stunning' },
      { name: 'Custom Date Range Filters', count: 3, sampleQuote: 'Need quarter-over-quarter comparisons' },
    ],
    suggestedAction: 'Deploy async background export worker with email notifications for large tables.',
    priorityScore: 65,
    revenueAtRisk: 52000,
  },
  {
    id: 'thm-4',
    name: 'Integrations & API',
    category: 'Ecosystem',
    description: 'Slack bot notifications, Linear/Jira issue tracking, and API rate limits.',
    count: 9,
    sentimentBreakdown: {
      positive: 6,
      neutral: 2,
      negative: 1,
    },
    avgSentimentScore: 0.52,
    growthRate: -5,
    subThemes: [
      { name: 'Slack Realtime Alerts', count: 5, sampleQuote: 'Slack bot alerts team instantly on negative reviews' },
      { name: 'Linear / Jira Sync', count: 3, sampleQuote: 'Bi-directional sync needed for engineering handoff' },
      { name: 'Webhooks & REST API', count: 1, sampleQuote: 'Great developer docs for REST API' },
    ],
    suggestedAction: 'Build official 1-click Linear App integration for automated bug creation.',
    priorityScore: 58,
    revenueAtRisk: 60000,
  },
  {
    id: 'thm-5',
    name: 'Onboarding & Setup',
    category: 'Product Adoption',
    description: 'Setup wizard, team member invites, and product walkthrough guides.',
    count: 8,
    sentimentBreakdown: {
      positive: 4,
      neutral: 3,
      negative: 1,
    },
    avgSentimentScore: 0.28,
    growthRate: -12,
    subThemes: [
      { name: 'Team Invites & Expiry', count: 5, sampleQuote: 'Invite links expire too fast' },
      { name: 'Interactive Product Tour', count: 3, sampleQuote: 'Clean UI and fast setup' },
    ],
    suggestedAction: 'Extend invite token validity to 7 days and add guided template selector.',
    priorityScore: 45,
    revenueAtRisk: 24000,
  },
];
